
package engine.gui;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.SwingConstants;


import engine.game.Scenario;
import engine.modele.entity.player.Player;

/**
 * Cette classe va creer l'interface qui affiche les informations du joueur.
 **/
public class InfoJoueur extends javax.swing.JFrame {

    private Player player = Scenario.player;

    /**
     * Creates new form InfoJoueur
     */
    public InfoJoueur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        JLabel message1 = new JLabel("");
        message1.setHorizontalAlignment(SwingConstants.CENTER);

        GroupLayout layout = new GroupLayout(getContentPane());
        layout.setHorizontalGroup(
                layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(message1, GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(231)
                                .addComponent(message1, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(25, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> new InfoJoueur().setVisible(true));
    }
}
